#!/bin/bash
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
id nginx || useradd -r -s /bin/false nginx
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
